[book]
authors = ["esteeschwarz"]
language = "en"
multilingual = false
src = "./mdbook/workflow/src"
title = "Corpus Class WrapUp"


[output.html]
git-repository-url = "https://github.com/esteeschwarz/HU-LX"
